apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: expense
    name: expense-trainee
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
   # above verbs are read only permissions. If you want to give write permissions then you can add "create", "update", "delete" verbs in the above list.