apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: expense
    name: expense-trainee
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
   # above verbs are read only permissions. If you want to give write permissions then you can add "create", "update", "delete" verbs in the above list.

# Now bind the role to the use using RoleBinding. RoleBinding is used to bind the role to the user or group or service account.

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: expense-trainee
    namespace: expense
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: expense-trainee
subjects:
- apiGroup: rbac.authorization.k8s.io # this is required to specify the api group for the user or group or service account. 
  kind: User
  name: Sudhir Kumar # change to your name or email id which is used to login to the cluster. This will give the permissions defined in the role to the user.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: expense-admin
rules:
- apiGroups: ["*"] # "" indicates the core all API group and "*" indicates all resources in that API group. So the above rule gives permissions to all resources in all API groups.
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: expense-admin
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: expense-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ramesh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: expense
rules:
- apiGroups: [""]
  resources: ["nodes","persistentvolumes","namespaces"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: expense
subjects:
- kind: User
  name: ramesh # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: expense
  apiGroup: rbac.authorization.k8s.io


